import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-slate-100">
      <body className="h-full">
        <div className="min-h-full flex justify-center">
          <div className="w-full max-w-md bg-white">{children}</div>
        </div>
      </body>
    </html>
  );
}
